-- MySQL Script generated by MySQL Workbench
-- Thu Oct  6 19:41:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bidding
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bidding
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bidding` DEFAULT CHARACTER SET utf8 ;
USE `bidding` ;

-- -----------------------------------------------------
-- Table `bidding`.`Measurement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bidding`.`Measurement` (
  `unit` VARCHAR(4) NOT NULL,
  `description` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`unit`),
  UNIQUE INDEX `Unit_UNIQUE` (`unit` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bidding`.`Contractor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bidding`.`Contractor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `companyName` VARCHAR(250) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `contactPerson` VARCHAR(250) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bidding`.`ItemGroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bidding`.`ItemGroup` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bidding`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bidding`.`Item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `description` TEXT NULL,
  `avgPrice` DECIMAL NOT NULL,
  `image` VARCHAR(250) NULL,
  `banner` VARCHAR(250) NULL,
  `unitOfMeasurement` VARCHAR(4) NOT NULL,
  `itemGroup` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `bidding`.`ItemGroup`
-- -----------------------------------------------------
START TRANSACTION;
USE `bidding`;
INSERT INTO `bidding`.`ItemGroup` (`id`, `name`) VALUES (1, 'Aluguel de maquinas');
INSERT INTO `bidding`.`ItemGroup` (`id`, `name`) VALUES (2, 'Materiais de Construção');
INSERT INTO `bidding`.`ItemGroup` (`id`, `name`) VALUES (3, 'Mão de obra');
INSERT INTO `bidding`.`ItemGroup` (`id`, `name`) VALUES (4, 'Aluguel de equipamentos');

COMMIT;


-- -----------------------------------------------------
-- Data for table `bidding`.`Item`
-- -----------------------------------------------------
START TRANSACTION;
USE `bidding`;
INSERT INTO `bidding`.`Item` (`id`, `name`, `description`, `avgPrice`, `image`, `banner`, `unitOfMeasurement`, `itemGroup`) VALUES (1, 'Terraplanagem', 'Projeto e Execução de Terraplenagem, Demolições e Remoção de entulho', 9600, 'https://img.freepik.com/fotos-gratis/tiro-de-angulo-alto-de-duas-escavadeiras-em-um-canteiro-de-obras_181624-7771.jpg', 'https://img.freepik.com/fotos-gratis/escavadeira-pesada-para-cavar-na-luz-do-dia_23-2149194838.jpg', 'MQ', NULL);
INSERT INTO `bidding`.`Item` (`id`, `name`, `description`, `avgPrice`, `image`, `banner`, `unitOfMeasurement`, `itemGroup`) VALUES (2, 'Acabamentos e revestimentos', 'Revestimentos naturais para paredes, pisos e piscinas e revestimento especiais', 5700, 'https://img.freepik.com/fotos-gratis/construtor-coloca-as-telhas-no-chao-o-reparo_493343-28515.jpg', 'https://img.freepik.com/fotos-gratis/tiler-trabalhando-na-renovacao-do-apartamento_23-2149278631.jpg', 'UN', NULL);
INSERT INTO `bidding`.`Item` (`id`, `name`, `description`, `avgPrice`, `image`, `banner`, `unitOfMeasurement`, `itemGroup`) VALUES (3, 'Supervisão de obras', 'Supervisão e Fiscalização de Obras.', 3400, 'https://img.freepik.com/free-photo/back-view-old-man-with-helmet-holding-laptop_23-2148269388.jpg', 'https://img.freepik.com/fotos-gratis/construcao-de-nova-casa-de-concreto_1398-2995.jpg', 'HS', NULL);
INSERT INTO `bidding`.`Item` (`id`, `name`, `description`, `avgPrice`, `image`, `banner`, `unitOfMeasurement`, `itemGroup`) VALUES (4, 'Escavação para fundações', 'Escavação manual e com maquinário, escavação de valas, escavações para fundação', 9800, 'https://img.freepik.com/fotos-gratis/maquinas-pesadas-e-trabalhadores-da-construcao-civil-trabalhando-em-um-edificio_181624-8234.jpg', 'https://img.freepik.com/fotos-gratis/escavadeira-para-cavar-com-luz-do-dia-ao-ar-livre_23-2149194792.jpg', 'MQ', NULL);
INSERT INTO `bidding`.`Item` (`id`, `name`, `description`, `avgPrice`, `image`, `banner`, `unitOfMeasurement`, `itemGroup`) VALUES (5, 'Serviços de infraestrutura', 'Dispositivos para o transporte de águas, gás, eletricidade e comunicações', 4120, 'https://img.freepik.com/fotos-gratis/um-eletricista-trabalha-em-uma-mesa-telefonica-com-um-cabo-eletrico-de-conexao_169016-15090.jpg', 'https://img.freepik.com/free-photo/electrical-technician-working-switchboard-with-fuses_169016-5512.jpg', 'HS', NULL);
INSERT INTO `bidding`.`Item` (`id`, `name`, `description`, `avgPrice`, `image`, `banner`, `unitOfMeasurement`, `itemGroup`) VALUES (6, 'Alvenaria', 'Serviços de alvenaria', 7050, 'https://img.freepik.com/fotos-gratis/barra-de-aco-no-local-de-construcao_1150-10124.jpg', 'https://img.freepik.com/fotos-gratis/trabalhador-da-construcao-civil-feminino-robusto-no-canteiro-de-obras_1150-10079.jpg', 'UN', NULL);

COMMIT;

