
-- -------------------------------------------------------------
-- For PostgreSQL keep the double quotes, for MySQL remove them
-- -------------------------------------------------------------

INSERT INTO item (name, description, "avgPrice", image, "banner", "unitOfMeasurement", "itemGroup") VALUES ('Terraplanagem','Projeto e Execução de Terraplenagem, Demolições e Remoção de entulho',9600,'https://img.freepik.com/fotos-gratis/tiro-de-angulo-alto-de-duas-escavadeiras-em-um-canteiro-de-obras_181624-7771.jpg','https://img.freepik.com/fotos-gratis/escavadeira-pesada-para-cavar-na-luz-do-dia_23-2149194838.jpg','MQ',NULL);
INSERT INTO item (name, description, "avgPrice", image, "banner", "unitOfMeasurement", "itemGroup") VALUES ('Acabamentos e revestimentos','Revestimentos naturais para paredes, pisos e piscinas e revestimento especiais',5700,'https://img.freepik.com/fotos-gratis/construtor-coloca-as-telhas-no-chao-o-reparo_493343-28515.jpg','https://img.freepik.com/fotos-gratis/tiler-trabalhando-na-renovacao-do-apartamento_23-2149278631.jpg','UN',NULL);
INSERT INTO item (name, description, "avgPrice", image, "banner", "unitOfMeasurement", "itemGroup") VALUES ('Supervisão de obras','Supervisão e Fiscalização de Obras.',3400,'https://img.freepik.com/free-photo/back-view-old-man-with-helmet-holding-laptop_23-2148269388.jpg','https://img.freepik.com/fotos-gratis/construcao-de-nova-casa-de-concreto_1398-2995.jpg','HS',NULL);
INSERT INTO item (name, description, "avgPrice", image, "banner", "unitOfMeasurement", "itemGroup") VALUES ('Escavação para fundações','Escavação manual e com maquinário, escavação de valas, escavações para fundação',9800,'https://img.freepik.com/fotos-gratis/maquinas-pesadas-e-trabalhadores-da-construcao-civil-trabalhando-em-um-edificio_181624-8234.jpg','https://img.freepik.com/fotos-gratis/escavadeira-para-cavar-com-luz-do-dia-ao-ar-livre_23-2149194792.jpg','MQ',NULL);
INSERT INTO item (name, description, "avgPrice", image, "banner", "unitOfMeasurement", "itemGroup") VALUES ('Serviços de infraestrutura','Dispositivos para o transporte de águas, gás, eletricidade e comunicações',4120,'https://img.freepik.com/fotos-gratis/um-eletricista-trabalha-em-uma-mesa-telefonica-com-um-cabo-eletrico-de-conexao_169016-15090.jpg','https://img.freepik.com/free-photo/electrical-technician-working-switchboard-with-fuses_169016-5512.jpg','HS',NULL);
INSERT INTO item (name, description, "avgPrice", image, "banner", "unitOfMeasurement", "itemGroup") VALUES ('Alvenaria','Serviços de alvenaria',7050,'https://img.freepik.com/fotos-gratis/barra-de-aco-no-local-de-construcao_1150-10124.jpg','https://img.freepik.com/fotos-gratis/trabalhador-da-construcao-civil-feminino-robusto-no-canteiro-de-obras_1150-10079.jpg','UN',NULL);
